export enum ambitoToken {
    inicio_raiz_1b = "inicio en raiz",
    general_nb = "búsqueda general",
    nodoactual_2b = "búsqueda desde nodo actual",
    nodoactual_1p = "selección nodo actual",
    padrenodo_2p = "selección de nodo padre",
    atributos = "selección de atributos",
    elementohijo_1b = "busqueda en nodo hijo"
}

export enum tipoToken {
    numero = "NUMERO",
    b = "/",
    bb = "//",
    pb = "./",
    pbb = ".//",
    ppb = "../",
    ppbb = "..//",
    cadena = "cadena",
    corchete1 = "[",
    corchete2 = "]",
    parentesis1 = "(",
    parentesis2 = ")",
    barravertical = "|",
    mas = "+",
    menos = "-",
    por = "*",
    div = "div",
    iwal = "=",
    noiwal = "!=",
    menorque = "<",
    menoriwal = "<=",
    mayorque = ">",
    mayoriwal = ">=",
    or = "or",
    and = "and",
    mod = "mod",
    arroba = "arroba",
    pr_ancestor = "ancestor",
    pr_ancestorself = "ancestor-or-self",
    pr_attribute = "attribute",
    pr_child = "child",
    pr_descendant = "descendant",
    pr_descendantself = "descendant-or-self",
    pr_following = "following",
    pr_followingself = "following-or-sibling",
    pr_namespace = "namespace",
    pr_parent = "parent",
    pr_preceding = "preceding",
    pr_precedingsibling = "preceding-sibling",
    pr_self = "self",
    dos_puntos2 = "::",
    id = "id",
}
