"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TiposXpath = void 0;
var TiposXpath;
(function (TiposXpath) {
    TiposXpath[TiposXpath["ID_SIMPLE"] = 0] = "ID_SIMPLE";
    TiposXpath[TiposXpath["ID_PREDICADO"] = 1] = "ID_PREDICADO";
    TiposXpath[TiposXpath["PREDICADO"] = 2] = "PREDICADO";
    TiposXpath[TiposXpath["DIAGONAL_SIMPLE"] = 3] = "DIAGONAL_SIMPLE";
    TiposXpath[TiposXpath["DIAGONAL_DOBLE"] = 4] = "DIAGONAL_DOBLE";
    TiposXpath[TiposXpath["PUNTO"] = 5] = "PUNTO";
    TiposXpath[TiposXpath["DOSPUNTOS"] = 6] = "DOSPUNTOS";
    TiposXpath[TiposXpath["DOSPUNTOSCONSECUTIVOS"] = 7] = "DOSPUNTOSCONSECUTIVOS";
    TiposXpath[TiposXpath["ASTERISCO"] = 8] = "ASTERISCO";
    TiposXpath[TiposXpath["ARROBA_ID"] = 9] = "ARROBA_ID";
    TiposXpath[TiposXpath["ARROBA_ASTERISCO"] = 10] = "ARROBA_ASTERISCO";
    TiposXpath[TiposXpath["FUNCION_NODE"] = 11] = "FUNCION_NODE";
    TiposXpath[TiposXpath["FUNCION_TEXT"] = 12] = "FUNCION_TEXT";
    TiposXpath[TiposXpath["FUNCION_LAST"] = 13] = "FUNCION_LAST";
    TiposXpath[TiposXpath["FUNCION_POSITION"] = 14] = "FUNCION_POSITION";
    TiposXpath[TiposXpath["METODO_ANCESTOR"] = 15] = "METODO_ANCESTOR";
    TiposXpath[TiposXpath["METODO_ANCESTOR_OR_SELF"] = 16] = "METODO_ANCESTOR_OR_SELF";
    TiposXpath[TiposXpath["METODO_ATRIBUTE"] = 17] = "METODO_ATRIBUTE";
    TiposXpath[TiposXpath["METODO_CHILD"] = 18] = "METODO_CHILD";
    TiposXpath[TiposXpath["METODO_DESCENDANT"] = 19] = "METODO_DESCENDANT";
    TiposXpath[TiposXpath["METODO_DESCENDANT_OR_SELF"] = 20] = "METODO_DESCENDANT_OR_SELF";
    TiposXpath[TiposXpath["METODO_FOLLOWING"] = 21] = "METODO_FOLLOWING";
    TiposXpath[TiposXpath["METODO_FOLLOWING_SIGLING"] = 22] = "METODO_FOLLOWING_SIGLING";
    TiposXpath[TiposXpath["METODO_PARENT"] = 23] = "METODO_PARENT";
    TiposXpath[TiposXpath["METODO_PRECEDING"] = 24] = "METODO_PRECEDING";
    TiposXpath[TiposXpath["METODO_PRECEDING_SIBLING"] = 25] = "METODO_PRECEDING_SIBLING";
    TiposXpath[TiposXpath["METODO_SELF"] = 26] = "METODO_SELF";
    TiposXpath[TiposXpath["REGLA_AUXILIAR"] = 27] = "REGLA_AUXILIAR";
    TiposXpath[TiposXpath["IDENTIFICADOR"] = 28] = "IDENTIFICADOR";
    TiposXpath[TiposXpath["STRING"] = 29] = "STRING";
    TiposXpath[TiposXpath["CADENA"] = 30] = "CADENA";
    TiposXpath[TiposXpath["INT"] = 31] = "INT";
    TiposXpath[TiposXpath["DOUBLE"] = 32] = "DOUBLE";
    TiposXpath[TiposXpath["BOOL"] = 33] = "BOOL";
    TiposXpath[TiposXpath["VOID"] = 34] = "VOID";
    TiposXpath[TiposXpath["STRUCT"] = 35] = "STRUCT";
    TiposXpath[TiposXpath["NULL"] = 36] = "NULL";
    TiposXpath[TiposXpath["ARRAY"] = 37] = "ARRAY";
})(TiposXpath = exports.TiposXpath || (exports.TiposXpath = {}));
