export enum TipoSeleccion {
    ACCESO_NODO_RAIZ = "ACCESO_NODO_RAIZ",
    SELECT_NODOS_FROM_NODO = "SELECT_NODOS_FROM_NODO",
    ERROR_SINTACTICO= "ERROR_SINTACTICO",
    ERROR_LEXICO = "ERROR_LEXICO",
    ERROR_SEMANTICO="ERROR_SEMANTICO"
}